resource "valsoperator_valssecret" "example" {
  name      = "example"
  namespace = "default"

  secret_ref {
    name     = "username"
    ref      = "ref+vault://secret/myapp/username"
    encoding = "text"
  }

  secret_ref {
    name     = "password"
    ref      = "ref+vault://secret/myapp/password"
    encoding = "text"
  }

  template {
    name  = "config.yaml"
    value = <<END
# Config generated by Vals-Operator on {{ now | date "2006-01-02" }}
username: {{.username}}
password: {{.password}}
END
  }
}
